### ISSUE TITLE
Relicense to MIT because AGPL is ew 

### ISSUE THREAD

**Issue by dominikaaaa** [Crystallinqq/Mercury-Client#1]
Or LGPL2.1+ (not LGPL2.1) due to license compatibility

**Comment by Tigermouthbear** [comment]
relicense to MIT 🧠

**Comment by Crystallinqq** [comment]
ok make a pr and sure im lazy :sob:

**Comment by cookiedragon234** [comment]
😹

**Comment by cookiedragon234** [comment]
Bella wants MIT cause under AGPL she cant add mercury code to KBlue???????????????

**Comment by dominikaaaa** [comment]
# :duck: :pinching_hand:
